apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-ws
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ws.externalPort }}
      targetPort: {{ .Values.service.ws.internalPort }}
      name: {{ .Values.service.ws.name }}
      protocol: TCP
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-http
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.externalPort }}
      targetPort: {{ .Values.service.http.internalPort }}
      name: {{ .Values.service.http.name }}
      protocol: TCP
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
