#!/bin/sh

T=$(mktemp /tmp/config.XXXXX)

cat <<HERE > $T
# This is the default config for file authentication
# If you use smth else, update this as well
auth:
  type: file
  options:
    path: ./users.yml
    hash: 'sha256'
    iterations: 100
    keyLength: 64
HERE

randString() {
	cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1
}

genPass() {
	docker run -it --entrypoint /bin/deepstream \
		-v $T:/etc/deepstream/config.yml \
		deepstreamio/deepstream.io:3.0.0 hash "$1"
}

for user in server-producer server-consumer frontend; do
	pass=$(randString)	

	echo "Username: $user"
	echo "Password: $pass"

  genPass $pass

	echo
done
